export const defaultData: Person[] = [
  {
    id: 1,
    name: "John Doe",
    age: 29,
    gender: "Male",
    email: "johndoe@example.com",
    phone: "123-456-7890",
    address: "123 Main St, City A, Country",
    occupation: "Engineer",
    company: "Tech Corp",
    salary: 50000,
    isActive: true,
    joinDate: "2023-01-15",
  },
  {
    id: 2,
    name: "Jane Smith",
    age: 32,
    gender: "Female",
    email: "janesmith@example.com",
    phone: "098-765-4321",
    address: "456 Elm St, City B, Country",
    occupation: "Designer",
    company: "Creative Studio",
    salary: 60000,
    isActive: false,
    joinDate: "2022-09-10",
  },
  {
    id: 3,
    name: "Michael Brown",
    age: 40,
    gender: "Male",
    email: "michaelbrown@example.com",
    phone: "234-567-8901",
    address: "789 Pine St, City C, Country",
    occupation: "Manager",
    company: "Business Solutions",
    salary: 75000,
    isActive: true,
    joinDate: "2021-03-20",
  },
  {
    id: 4,
    name: "Emily Johnson",
    age: 25,
    gender: "Female",
    email: "emilyjohnson@example.com",
    phone: "345-678-9012",
    address: "101 Maple St, City D, Country",
    occupation: "Developer",
    company: "Web Dev Inc.",
    salary: 55000,
    isActive: true,
    joinDate: "2023-06-10",
  },
  {
    id: 5,
    name: "Chris Lee",
    age: 37,
    gender: "Male",
    email: "chrislee@example.com",
    phone: "456-789-0123",
    address: "202 Oak St, City E, Country",
    occupation: "Analyst",
    company: "Finance Group",
    salary: 68000,
    isActive: false,
    joinDate: "2020-11-25",
  },
  {
    id: 6,
    name: "Sophia White",
    age: 28,
    gender: "Female",
    email: "sophiawhite@example.com",
    phone: "567-890-1234",
    address: "303 Birch St, City F, Country",
    occupation: "Accountant",
    company: "Financial Services",
    salary: 62000,
    isActive: true,
    joinDate: "2023-05-14",
  },
  {
    id: 7,
    name: "Daniel Green",
    age: 35,
    gender: "Male",
    email: "danielgreen@example.com",
    phone: "678-901-2345",
    address: "404 Cedar St, City G, Country",
    occupation: "Consultant",
    company: "Consulting Firm",
    salary: 71000,
    isActive: true,
    joinDate: "2021-10-09",
  },
  {
    id: 8,
    name: "Olivia Martin",
    age: 26,
    gender: "Female",
    email: "oliviamartin@example.com",
    phone: "789-012-3456",
    address: "505 Willow St, City H, Country",
    occupation: "Marketing Specialist",
    company: "Marketing Pros",
    salary: 58000,
    isActive: false,
    joinDate: "2020-12-19",
  },
  {
    id: 9,
    name: "James Wilson",
    age: 44,
    gender: "Male",
    email: "jameswilson@example.com",
    phone: "890-123-4567",
    address: "606 Fir St, City I, Country",
    occupation: "Director",
    company: "Enterprise Solutions",
    salary: 95000,
    isActive: true,
    joinDate: "2019-04-07",
  },
  {
    id: 10,
    name: "Amelia Scott",
    age: 31,
    gender: "Female",
    email: "ameliascott@example.com",
    phone: "901-234-5678",
    address: "707 Spruce St, City J, Country",
    occupation: "Content Writer",
    company: "Media Hub",
    salary: 54000,
    isActive: true,
    joinDate: "2022-02-25",
  },
  {
    id: 11,
    name: "Henry Clark",
    age: 39,
    gender: "Male",
    email: "henryclark@example.com",
    phone: "123-345-6789",
    address: "808 Palm St, City K, Country",
    occupation: "Operations Manager",
    company: "Logistics Co.",
    salary: 70000,
    isActive: true,
    joinDate: "2021-09-12",
  },
  {
    id: 12,
    name: "Mia Roberts",
    age: 27,
    gender: "Female",
    email: "miaroberts@example.com",
    phone: "234-456-7890",
    address: "909 Cypress St, City L, Country",
    occupation: "Project Manager",
    company: "Projects Inc.",
    salary: 65000,
    isActive: false,
    joinDate: "2023-04-03",
  },
  {
    id: 13,
    name: "Jack Turner",
    age: 33,
    gender: "Male",
    email: "jackturner@example.com",
    phone: "345-567-8901",
    address: "1010 Redwood St, City M, Country",
    occupation: "Sales Manager",
    company: "Retail Corp",
    salary: 72000,
    isActive: true,
    joinDate: "2020-08-17",
  },
  {
    id: 14,
    name: "Grace Hill",
    age: 30,
    gender: "Female",
    email: "gracehill@example.com",
    phone: "456-678-9012",
    address: "1111 Cedar St, City N, Country",
    occupation: "UI/UX Designer",
    company: "Design Agency",
    salary: 59000,
    isActive: true,
    joinDate: "2022-05-26",
  },
  {
    id: 15,
    name: "Leo Walker",
    age: 41,
    gender: "Male",
    email: "leowalker@example.com",
    phone: "567-789-0123",
    address: "1212 Maple St, City O, Country",
    occupation: "IT Specialist",
    company: "IT Solutions",
    salary: 81000,
    isActive: false,
    joinDate: "2020-01-08",
  },
  {
    id: 16,
    name: "Isabella Young",
    age: 34,
    gender: "Female",
    email: "isabellayoung@example.com",
    phone: "678-890-1234",
    address: "1313 Fir St, City P, Country",
    occupation: "HR Manager",
    company: "Human Resources",
    salary: 67000,
    isActive: true,
    joinDate: "2019-11-21",
  },
  {
    id: 17,
    name: "Lucas King",
    age: 38,
    gender: "Male",
    email: "lucasking@example.com",
    phone: "789-901-2345",
    address: "1414 Pine St, City Q, Country",
    occupation: "Business Analyst",
    company: "Consulting Co.",
    salary: 64000,
    isActive: false,
    joinDate: "2021-07-15",
  },
  {
    id: 18,
    name: "Ava Adams",
    age: 24,
    gender: "Female",
    email: "avaadams@example.com",
    phone: "890-012-3456",
    address: "1515 Oak St, City R, Country",
    occupation: "Researcher",
    company: "Science Labs",
    salary: 53000,
    isActive: true,
    joinDate: "2023-03-28",
  },
  {
    id: 19,
    name: "Ethan Baker",
    age: 45,
    gender: "Male",
    email: "ethanbaker@example.com",
    phone: "901-123-4567",
    address: "1616 Elm St, City S, Country",
    occupation: "CEO",
    company: "Tech Innovations",
    salary: 150000,
    isActive: true,
    joinDate: "2018-06-15",
  },
  {
    id: 20,
    name: "Lily Harris",
    age: 29,
    gender: "Female",
    email: "lilyharris@example.com",
    phone: "012-234-5678",
    address: "1717 Cherry St, City T, Country",
    occupation: "Consultant",
    company: "Business Solutions",
    salary: 55000,
    isActive: false,
    joinDate: "2022-12-01",
  },
];

export type Person = {
  id: number;
  name: string;
  age: number;
  gender: string;
  email: string;
  phone: string;
  address: string;
  occupation: string;
  company: string;
  salary: number;
  isActive: boolean;
  joinDate: string;
};
